language: node_js
services:
  - redis-server
cache: yarn
before_install:
- cp .env.example .env
script:
- yarn test
- rvm install 2.3.1
- rvm use 2.3.1
- gem install danger --no-ri --no-rdoc
- danger
after_success:
- test $TRAVIS_PULL_REQUEST = false && test $TRAVIS_BRANCH = "master" && yarn build
notifications:
  email: false
  slack:
    secure: "UG0vSapdUYSuigMPWFiZQB31ZO4X4Vy/pL8CiCqyHvthM1RSSxTaMHLiH36osbj8WRxOTPu4M1D20S7uChvJdPR4b2YYVsxltEl9S1t8+AVfFcJHALbcwgJ9u5CbyUqU28ozL5L+kHhkI6disU8l3bx2yTSl/YJhI913F6iK2MKXgMIsRVhLGfo2akTWdmLW0Ih4y4y6FKryR9HHNcxElJ+zve7NUZtmdlEKD1aUN0wlLpwkKXLZ5DD7O/ZGJxrUJIl/chWTIbsuXoFFZxihFo/7dw0K3/jcHoG1mJMRUJpryndeTFan9YdKoqvAjKKhFBXb0PDO5gI5eE0BNCtrp0m9HUU55xmIFn8sZVG6TjbzLqzpajrlKnU+0bFehsuZqJGVN+Io80iM7nohhS1WbJ6Gur01Iuj+VMwspyI+FBIiveXqcWTGkEq52kt8Q/5G+Y0pkXd9zWlOihN0C4v7vWIX/rg+JVmPv6zkb0308zBe2kE+u9t15KDEOxPh+p1inUj8GL4vz71m/WQCgGbk/RLAvLjzSpyhh+i2d9NnDJEpH5L6ZwuTWMHLw4zwag/PIXmGfeSl8zGJ76ZUiyWWY0efbvATGPTff7VESVYlabCFNWOKfpoX64cg52NOzx/p9KugmMhIHnoX8D00C2ANin5Nqo8az3cGB83YnSqJ6DU="
